version: '3.8'
services:
  eureka-server:
    image: melowetty/eureka-server-perm-helper
    ports:
      - $EUREKA_PORT:$EUREKA_DOCKER_PORT
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$EUREKA_SERVER_ACTIVE_PROFILE
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  api-gateway:
    image: melowetty/api-gateway-perm-helper
    depends_on:
      - eureka-server
    ports:
      - $GATEWAY_PORT:$GATEWAY_DOCKER_PORT
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$GATEWAY_ACTIVE_PROFILE
      - APP_SECURITY_PRIVATE-KEY=$TELEGRAM_BOT_PRIVATE_KEY
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  users-service:
    image: users-service
    depends_on:
      - eureka-server
      - users-service-mongodb
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - SPRING_DATA_MONGODB_HOST=$USERS_SERVICE_MONGODB_HOST
      - SPRING_DATA_MONGODB_PORT=$USERS_SERVICE_MONGODB_PORT
      - SPRING_DATA_MONGODB_DATABASE=$USERS_SERVICE_MONGODB_DATABASE
      - SPRING_DATA_MONGODB_USERNAME=$USERS_SERVICE_MONGODB_USERNAME
      - SPRING_DATA_MONGODB_PASSWORD=$USERS_SERVICE_MONGODB_PASSWORD
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always
  users-service-mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USERS_SERVICE_MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$USERS_SERVICE_MONGODB_PASSWORD
    ports:
      - $USERS_SERVICE_MONGODB_PORT:$USERS_SERVICE_MONGODB_PORT
    volumes:
      - users-service-db-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  users-service-db-data: