version: '3.8'
services:
  eureka-server:
    image: melowetty/eureka-server-perm-helper
    ports:
      - $EUREKA_PORT:$EUREKA_DOCKER_PORT
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$EUREKA_SERVER_ACTIVE_PROFILE
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  api-gateway:
    image: melowetty/api-gateway-perm-helper
    depends_on:
      - eureka-server
    ports:
      - $GATEWAY_PORT:$GATEWAY_DOCKER_PORT
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$GATEWAY_ACTIVE_PROFILE
      - APP_SECURITY_PRIVATE-KEY=$TELEGRAM_BOT_PRIVATE_KEY
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  users-service:
    image: users-service
    depends_on:
      - eureka-server
      - postgresdb-users-service
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb-users-service:$POSTGRESDB_USERS_SERVICE_DOCKER_PORT/$USERS_SERVICE_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$USERS_SERVICE_DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$USERS_SERVICE_DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  postgresdb-users-service:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$USERS_SERVICE_DB_USERNAME
      - POSTGRES_PASSWORD=$USERS_SERVICE_DB_PASSWORD
      - POSTGRES_DB=$USERS_SERVICE_DB_NAME
    ports:
      - $POSTGRESDB_USERS_SERVICE_LOCAL_PORT:$POSTGRESDB_USERS_SERVICE_DOCKER_PORT
#    volumes:
#      - users-service-db:/var/lib/postgres
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1