version: '3.8'
services:
  eureka-server:
    image: melowetty/eureka-server-perm-helper
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    volumes:
      - ./build:/home/gradle/project/build
    ports:
      - $EUREKA_PORT:$EUREKA_DOCKER_PORT
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  api-gateway:
    image: melowetty/api-gateway-perm-helper
    depends_on:
      - eureka-server
    build:
      context: ./
      dockerfile: ./api-gateway/Dockerfile
    volumes:
      - ./build:/home/gradle/project/build
    ports:
      - $GATEWAY_PORT:$GATEWAY_DOCKER_PORT
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - APP_SECURITY_PRIVATE-KEY=$PRIVATE_KEY
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

  users-service:
    image: melowetty/users-service-perm-helper
    depends_on:
      - eureka-server
      # - postgresdb-users-service
    build:
      context: ./
      dockerfile: ./users-service/Dockerfile
    volumes:
      - ./build:/home/gradle/project/build
    env_file: ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_SECURITY_PRIVATE-KEY=$PRIVATE_KEY
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=$EUREKA_DEFAULT_ZONE
    restart: always

#  postgresdb-users-service:
#    image: postgres
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - POSTGRES_USER=$DB_USERNAME
#      - POSTGRES_PASSWORD=$DB_PASSWORD
#      - POSTGRES_DB=$DB_NAME
#    ports:
#      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
#    volumes:
#      - db:/var/lib/postgres
